version: '3.8'

services:
  database:
    build: ./database/
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: credentials
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    # volumes:
    #   - ./database/pg_data:/var/lib/postgresql/data
    networks:
      - login-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d credentials"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend/
    container_name: backend
    restart: always
    environment:
      DATABASE_URI: postgresql://admin:admin@database:5432/credentials
      PYTHONUNBUFFERED: 1
      PYTHONPATH: /app
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/app/backend
    depends_on:
      database:
        condition: service_healthy
    networks:
      - login-network

  frontend:
    build: ./frontend/
    container_name: frontend
    restart: always
    ports:
      - "8050:8050"
    depends_on:
      - backend
    networks:
      - login-network

networks:
  login-network:
    driver: bridge
